# Basic
title: Alan's时光轴
subtitle: 生活的智慧大概就在于遇事问个为什么。 —— 巴尔扎克
welcome_message: <a href="https://github.com/JianHuaTongXue" target="_blank">欢迎光临</a>
description: Hello，我是Alan，是个 Android 开发者。
creator: <a href="https://linjianhua.me">Alan</a>

url: "https://linjianhua.me"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: My Projects, url: 'https://github.com/JianHuaTongXue'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: disqus_kyoGEZfI29
    #duoshuo: linjianhua 
    
# Social
social:
    weibo: JianHuaTongXue
    github: JianHuaTongXue
    twitter: JianHuaTongXue
    gplus: JianHuaTongXue
    mail: linjianhua.me@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
